$(window).scroll(function(){
    var scrollTop = $(window).scrollTop();
    console.log(scrollTop)
    if(scrollTop>0){
        $(".navbar").addClass("bg-white").removeClass("bg-none")
    }else{
        $(".navbar").addClass("bg-none").removeClass("bg-white")
    }
})
$(function(){
    $(".shouye").click(function(){
        $("html,body").animate({scrollTop:0},700)
    })
    $(".guanyu").click(function(){
        $("html,body").animate({scrollTop:843},700)
    })
    $(".aihao").click(function(){
        $("html,body").animate({scrollTop:1399},700)
    })
    $(".ceshi").click(function(){
        $("html,body").animate({scrollTop:2024},700)
    })
    $(".nengli").click(function(){
        $("html,body").animate({scrollTop:2664},700)
    })
    $(".lianxi").click(function(){
        $("html,body").animate({scrollTop:3025},700)
    })

})